Test with Julienne
BerkeleyLab/caffeine pull request #169
Opened 2024-12-28 19:03 UTC by rouson

2025-01-02 16:16 UTC, everythingfunctional reviewed
I haven't reviewed the changes the tests yet, but I have a few higher level comments so far.

1. You need to add an `fpm.toml` file in the `test-termination` folder. At present the instructions in the `test-termination/README.md` do not work. The `fpm.toml` I created is listed below.
2. It is unclear from the output whether the tests pass or fail. I would recommend putting together some sort of script that checks the output of each individual test rather than have users try to inspect the outputs and determine pass/fail manually. This should make getting the CI to work easier as well.
3. I would have made the switch to Julienne a separate PR, as the stop tests don't really depend on the test framework and vice-versa.
4. I think on balance the switch to Julienne might be the right move, but I think it's worth pointing out some of the important differences:
   1. You get less detailed output from running the test suite. i.e. it doesn't report how many or what values are being compared. This could make debugging failing tests (or erroneously passing tests) more difficult.
   2. The framework is simpler, and it is one you control.
5. I think you could adapt `veggies` in a similar way as you did with `julienne`, so if you're curious to try it, I could point you at the few things you'd want/need to overload.

example `fpm.toml` file
```toml
name = "test-termination"
version = "0.4.1"
license = "BSD"
author = ["Damian Rouson", "Brad Richardson", "Katherine Rasmussen", "Dan Bonachea"]
maintainer = "rouson@lbl.gov"
copyright = "2021-2024 UC Regents"

[dependencies]
caffeine = {path = ".."}

[build]
link = ["gasnet-smp-seq", "gcc", "m"]
```

2025-01-02 20:53 UTC, rouson commented
@everythingfunctional thanks for the quick review!
 
> 1. You need to add an `fpm.toml` file in the `test-termination` folder. At present the instructions in the `test-termination/README.md` do not work. The `fpm.toml` I created is listed below.

Good catch.  I just pushed my `fpm.toml`, which I mistakenly didn't add before. This required `git add -f` because `fpm.toml` is in the `.gitignore` due to the top-level manifest being generated by `install.sh`.

> 2. It is unclear from the output whether the tests pass or fail. I would recommend putting together some sort of script that checks the output of each individual test rather than have users try to inspect the outputs and determine pass/fail manually. This should make getting the CI to work easier as well.

That's the plan.  I'm hoping @ktras can work on this.

> 3. I would have made the switch to Julienne a separate PR, as the stop tests don't really depend on the test framework and vice-versa.

I agree. If we decide against the switch to Julienne, I'll create a separate PR to replace the old program termination tests with the new ones.

> 4. I think on balance the switch to Julienne might be the right move, but I think it's worth pointing out some of the important differences:
>    
>    1. You get less detailed output from running the test suite. i.e. it doesn't report how many or what values are being compared. This could make debugging failing tests (or erroneously passing tests) more difficult.

This morning's release of Julienne 1.6.0 adds this information in diagnostic output.  This issue has been bugging me for a while, but it took some focused time over the break to think of how to add such diagnostic output in backwards-compatible way.   Of course, there aren't many projects using Julienne yet (two-ish) but it would be nice to not have to rewrite multiple projects' test suites all at once.  Fortunately I finally figured out a backwards-compatible path and that's in Julienne 1.6.0.

>    2. The framework is simpler, and it is one you control.

> 5. I think you could adapt `veggies` in a similar way as you did with `julienne`, so if you're curious to try it, I could point you at the few things you'd want/need to overload.

Very cool. It would probably be useful info for learning purposes either way so pointers are welcome.

2025-01-02 21:02 UTC, bonachea requested changes
Made some initial observations based on a quick skim of the high-level changes.

I have not yet dived into review of the test code.

2025-01-06 20:07 UTC, rouson commented on test-termination/fpm.toml
@bonachea if we agree that the new approach is a step in the right direction, then it might make sense to merge the termination-tests as is before more thoroughly addressing #137.  How does that sound?

2025-01-06 20:13 UTC, rouson commented
As of commit fcf2fa8, this PR now adds the capability for diagnostic output in the event of a test failure for all tests except those in `test/prif_allocate_test_m.F90 `.  Adding diagnostic output to the latter test will likely require a relatively minor update to Julienne.  That means 48 of 52 tests can produce diagnostic output.  I think that's a sufficiently large fraction that the PR could be merged before adding the diagnostic output in the four missing cases.

2025-01-06 21:00 UTC, bonachea commented on manifest/fpm.toml.template
> +assert = {git = "https://github.com/berkeleylab/assert.git", tag = "2.0.0"}
As agreed in our meeting, I'll be working on this upgrade as a separate PR

2025-01-06 21:04 UTC, bonachea commented on test-termination/fpm.toml
I agree we shouldn't hold up this PR waiting for a complete solution to #137. I've changed the PR description to stop claiming a complete fix to that issue, so that GitHub hopefully won't automatically close it.

I'm not yet prepared to approve a merge of this PR as-is, let's plan to discuss on Wednesday.

2025-01-06 21:46 UTC, bonachea requested changes
Made some additional observations. 

Right now my biggest concern with this PR is that it updates an (old?) snapshot of of the test suite, which is continuing to evolve in several other in-flight PRs. I don't want this PR to become a blocker for merging PRs that add Caffeine features (with corresponding test code that naturally will semantically conflict with this PR). 

Given a choice between reaching PRIF 0.5 compliance (a client-facing feature goal) and replacing an internal test harness, I'd currently lean towards prioritizing the former. Does the proposed switch from Veggies to Julienne provide any direct benefit to library clients, or is this purely a maintainability upgrade that mostly benefits Caffeine developers? 

Let's plan to discuss this further in our meeting this week.

2025-01-06 21:46 UTC, bonachea commented on test/prif_test_s.f90
> +    call prif_co_reduce(boolean, c_funloc(both))
This is using the PRIF 0.4 version of `prif_co_reduce`, and will break when we upgrade the implementation to PRIF 0.5, which significantly complicates the code needed to invoke `prif_co_reduce` (see PR #158).

Moreover there's no semantic reason to use a custom reduction function here. Please convert the boolean to an integer and use `prif_co_sum` or `prif_co_max` instead, to avoid the mess mentioned above.

2025-01-06 21:46 UTC, bonachea commented on test/prif_co_reduce_test_m.F90
Changes in this file massively conflict with the complete rewrite in-progress in PR #158 to accommodate the PRIF 0.5 changes to collectives.

2025-01-06 21:46 UTC, bonachea commented on test/prif_co_max_test_m.F90
Changes in this file will conflict with the changes in-progress in PR #158 to accommodate the PRIF 0.5 changes to collectives.

2025-01-06 21:46 UTC, bonachea commented on test/prif_co_min_test_m.F90
Changes in this file will conflict with the changes in-progress in PR #158 to accommodate the PRIF 0.5 changes to collectives.

2025-01-06 21:46 UTC, bonachea commented on test/prif_co_sum_test_m.F90
Changes in this file will conflict with the changes in-progress in PR #158 to accommodate the PRIF 0.5 changes to collectives.

2025-01-06 21:46 UTC, bonachea commented on test/prif_teams_test_m.F90
Changes in this file massively conflict with the changes in-progress in PR #171, where this test was greatly expanded to complete coverage for the PRIF 0.5 implementation of teams.

2025-01-16 23:37 UTC, bonachea commented
The simple file renames for `test/*` proposed as part of this PR have now been merged in standalone PR #174, as previously discussed and agreed.

This PR will eventually need a rebase to resolve that conflict and also semantic conflicts with PR #171 and #175 that have also been merged. However as discussed work on this PR should probably be deferred until after PR #158 is completed and the test suite reaches a point of stability with PRIF 0.5, to avoid another redundant round of conflict resolution.

2025-03-31 20:40 UTC, rouson commented
This branch is out of date and Julienne has evolved with some breaking changes.  We can delete this branch and create a new PR after 
1. Julienne 2.0.0 releases and
2. Any other work that would touch the test suite is paused.

2025-03-31 20:40 UTC, closed without merging