Add all remaining `prif` interfaces
BerkeleyLab/caffeine pull request #48
Opened 2023-12-18 00:35 UTC by ktras

Add all remaining `prif` interfaces based on design doc revision 0.2

2023-12-18 20:32 UTC, bonachea requested changes
Overall LGTM. 

I did NOT attempt to exhaustively compare all the subroutine signatures for spec conformance, although that's something that eventually needs to be audited, and ideally supported with test code that ensures calls compile as intended.

2023-12-18 20:32 UTC, bonachea commented on src/prif.f90
Missing new `prif_critical_type`, which should probably be just a renamed `prif_lock_type`

2023-12-18 21:12 UTC, everythingfunctional approved these changes
A did a brief once-over and nothing jumps out. LGTM

2023-12-19 02:13 UTC, ktras commented on src/prif.f90
Done.

2023-12-19 03:27 UTC, bonachea approved these changes
Removing `pure` from functions internal to caffeine is probably overkill, but I have no specific objection.

The important part is to match the specified `prif_` interfaces at the top.

2023-12-19 03:31 UTC, ktras commented
> Removing `pure` from functions internal to caffeine is probably overkill, but I have no specific objection.
> 
> The important part is to match the specified `prif_` interfaces at the top.

@bonachea, I agree. I only removed `pure` from functions that I had to based on the cascading affects of `pure` being removed from some of the `prif_` interfaces that called other `pure` functions and no longer can. Thanks for the review!

2023-12-19 03:31 UTC, merged