add tests exposing co_broadcast and co_reduce bugs
BerkeleyLab/caffeine pull request #72
Opened 2024-03-06 22:01 UTC by everythingfunctional

To demonstrate the presence of the bugs you can run the isolated tests with either:

```text
GASNET_PSHM_NODES=2 ./build/run-fpm.sh test -- -f '(caffeinate|co_broadcast)' -f '(caffeinate|derived type)' -d
```
or
```text
GASNET_PSHM_NODES=2 ./build/run-fpm.sh test -- -f '(caffeinate|co_reduce)' -f '(caffeinate|derived type)' -d
```

2024-03-07 20:02 UTC, bonachea commented
Is there an open issue for these known defects?

If not, please open one with at least a minimal description of the failure.

On a related note, does our CI infrastructure have a way to mark "known failures"? If not, won't merging this result in CI failure for even unrelated PRs? 

We should probably discuss our policy for how to handle known defects: specifically whether tests revealing a known failure should be committed pre-emptively with some kind of known failure indicator, or whether known defect reproducers should remain only in the issue tracker until there is a PR that repairs the defect and also adds a regression test for the fixed defect.

2024-03-07 20:04 UTC, bonachea requested changes
Not convinced this should be merged as-is if it results in breaking CI for all PRs

2024-03-07 21:47 UTC, everythingfunctional commented
Yeah, totally wasn't expecting to merge this until we had a fix for each, but wanted to have concrete examples for discussion. I'll open an issue as well.

2025-01-16 23:50 UTC, bonachea commented
The bugs outlined in this PR were defects in the PRIF rev 0.4 specification that have since been resolved with specification and interface changes published in [PRIF revision 0.5](https://dx.doi.org/10.25344/S4CG6G). Here are the relevant changelog entries:

* Update argument list to prif_co_reduce to use operation_wrapper and add cdata argument
* Clarify the semantics of derived types passed to prif_co_broadcast

see the document for further details.

The interface defects exposed by this PR are now resolved in specification, and implementation work is ongoing in #158 that supersedes this PR.

2025-01-16 23:50 UTC, closed without merging