Add `unimplemented` routine and calls to it in any procedures not yet implemented
BerkeleyLab/caffeine pull request #75
Opened 2024-03-14 21:20 UTC by ktras

2024-03-14 23:05 UTC, bonachea requested changes
Not a blocker for this PR, but tangentially relevant is issue #50 where we'd identify "anything else" that belongs in the implementation with an `unimplemented` tag.

2024-03-15 20:10 UTC, ktras commented on src/caffeine/prif_private_s.f90
> +    error stop proc_name // " is not yet implemented"
Great catch! Updated.

2024-03-15 20:13 UTC, ktras commented
> Not a blocker for this PR, but tangentially relevant is issue #50 where we'd identify "anything else" that belongs in the implementation with an `unimplemented` tag.

I have updated issue #50 with clear todo items to be addressed in a future PR.

2024-03-16 06:28 UTC, bonachea approved these changes
LGTM!

2024-03-18 14:09 UTC, everythingfunctional approved these changes

2024-03-18 18:11 UTC, merged